import Head from "next/head";

import initDB from "../lib/db";
import { playersStatsCounter } from "../statsCounters/playersStatsCounter.tsx";
import { PlayerStats } from "../types/playerStats.type";
import { Heading } from "@chakra-ui/react";
import PlayersStatsTable from "../components/PlayersStatsTable";

export async function getStaticProps() {
  await initDB();
  const playerStats = await playersStatsCounter();
  return {
    props: {
      playerStats,
    },
  };
}

type Props = {
  playerStats: PlayerStats;
};

const Home: React.FC<Props> = ({ playerStats }) => {
  return (
    <>
      <Head>
        <title>Kicker Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading textAlign="center" py={10}>Kicker Stats</Heading>
        <PlayersStatsTable playerStats={playerStats} />
      </main>
    </>
  );
};

export default Home;
