import Head from "next/head";
import {
  Heading,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
} from "@chakra-ui/react";

import PlayersStatsTable from "../components/PlayersStatsTable";

import initDB from "../lib/db";
import getDbData from "../lib/getDbData";
import { playersStatsCounter } from "../statsCounters/playersStatsCounter";
import { tournamentsStatsCounter } from "../statsCounters/tournamentsStatsCounter";
import { PlayerStats } from "../types/playerStats.type";
import TournamentStatsTable from "../components/TournamentStatsTable";
import { TournamentStats } from "../types/tournamentStats.type";

export async function getStaticProps() {
  await initDB();
  const dbData = await getDbData();
  const playerStats = playersStatsCounter(dbData);
  const tournamentStats = tournamentsStatsCounter(dbData);

  return {
    props: {
      playerStats,
      tournamentStats,
    },
  };
}

type Props = {
  playerStats: PlayerStats;
  tournamentStats: TournamentStats;
};

const Home: React.FC<Props> = ({ playerStats, tournamentStats }) => {
  return (
    <>
      <Head>
        <title>Kicker Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading textAlign="center" py={10}>
          Kicker Stats
        </Heading>
        <Tabs variant="enclosed" isLazy id="tabs">
          <TabList>
            <Tab>Player Stats</Tab>
            <Tab>Tournament Stats</Tab>
          </TabList>
          <TabPanels>
            <TabPanel>
              <PlayersStatsTable playerStats={playerStats} />
            </TabPanel>
            <TabPanel>
              <TournamentStatsTable tournamentStats={tournamentStats} />
            </TabPanel>
          </TabPanels>
        </Tabs>
      </main>
    </>
  );
};

export default Home;
